apiVersion: v1
kind: Service
metadata:
  name: alice-{{ default "staging" .Release.Namespace }}-php
  labels:
    tier: backend
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9000
  selector:
    app: alice-{{ default "staging" .Release.Namespace }}-php
    tier: backend
